CREATE TABLE Pessoa ( ID INT PRIMARY KEY AUTO_INCREMENT, Nome VARCHAR(255) NOT NULL,
Sobrenome VARCHAR(255), DataNascimento DATE, Email VARCHAR(255) UNIQUE NOT NULL, Telefone
VARCHAR(20), Endereco VARCHAR(255), Cidade VARCHAR(100), Estado VARCHAR(50), CEP
VARCHAR(10), CPF_CNPJ VARCHAR(14) );desafio_first_decision